// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "78af41a2-0383-436c-8668-3ee5f80fd8fe";

const char SSID[]               = "ff";    // Network SSID (name)
const char PASS[]               = "12345678";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "?OPu6JpSB?rDgqxFSC0uh8!qf";    // Secret device password

void onPasswordChange();
//void onPassChange();
//void onMyVarChange();

String password;
int pass;
bool myVar;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(password, READWRITE, ON_CHANGE, onPasswordChange);
  //ArduinoCloud.addProperty(pass, READWRITE, ON_CHANGE, onPassChange);
  //ArduinoCloud.addProperty(myVar, READWRITE, ON_CHANGE, onMyVarChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);