# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBjO70eVhQ93rBUvqsasC9JzXVLyk4b4
"""

!pip install firebase-admin
!pip install twilio

import firebase_admin
from firebase_admin import credentials, db
!pip install twilio
from twilio.rest import Client
import time

# Firebase credentials (use environment variables or secure file storage in production)
firebase_credentials = {
    "type": "service_account",
    "project_id": "adpsr-75e1f",
    "private_key_id": "YOUR_PRIVATE_KEY_ID",
    "private_key": "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY\n-----END PRIVATE KEY-----\n",
    "client_email": "firebase-adminsdk-7fyvc@adpsr-75e1f.iam.gserviceaccount.com",
    "client_id": "107099221824990410869",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-7fyvc%40adpsr-75e1f.iam.gserviceaccount.com",
    "universe_domain": "googleapis.com"
}

# Twilio credentials
account_sid = "ACd0820c8fb546c38be1760536009548cc"
auth_token = "a07946d79b75d7a24937ba7ffcf5f083"

# Initialize Firebase Admin SDK
if not firebase_admin._apps:
    cred = credentials.Certificate(firebase_credentials)
    firebase_admin.initialize_app(cred, {
        'databaseURL': 'https://adpsr-75e1f-default-rtdb.firebaseio.com/'
    })

# Initialize Twilio Client
client = Client(account_sid, auth_token)
listp = ["1234"]
# Function to send an alert via Twilio
def alert():
    call = client.calls.create(
        twiml='<Response><Say>You are receiving this call because there has been a suspicious entry at the door. Please be alerted.</Say></Response>',
        to='+918247341184',
        from_='+15856693126'
    )
    print("Alert sent!")

# Fetch data from Firebase Realtime Database
def fetch_data_from_firebase(path):
    ref = db.reference(path)  # Specify the database path
    data = ref.get()
    return data

# Comparison function to calculate similarity
def compare(value):
    maxsim = 0
    if len(value) == 0:
        return 0
    for expected_password in listp:
        print(expected_password)
        count = 0
        expected_password_list = list(expected_password)
        value_list = list(value)
        for i in range(len(expected_password_list)):
            for j in range(len(value_list)):
                if value_list[j] == expected_password_list[i]:
                    count += 1
                    expected_password_list[i] = '&'
                    value_list[j] = '.'
                    break  # Stop searching for this character in `value_list`
        similarity = count / len(value)
        if similarity > maxsim:
            maxsim = similarity
    return maxsim

# Infinite monitoring loop
k = 0
while True:
    try:
        path1 = f'Entries/Entry{k}/typed'
        status1 = fetch_data_from_firebase(path1)
        l = 1
        while True:
            try:
                path2 = f'Passwords/pass{l}'
                status2 = fetch_data_from_firebase(path2)
                if status2:
                    print(f"Updating passwords from pass{l}...")
                    for key, value in status2.items():
                        print(f"Key: {key}, Value: {value}")
                        if len(listp) > l:
                            print("chec")
                            listp[l] = value
                        else:
                            print("did")
                            listp.append(value)
                    l += 1
                else:
                    print(l,"done")
                    break
            except Exception as e:
                print(f"Error fetching passwords: {e}. Retrying...")
                time.sleep(5)

        if status1:
            print(f"Processing Entry {k}...")
            for key, value in status1.items():
                print(f"Key: {key}, Value: {value}")
                similarity_score = compare(value)
                print(f"Similarity Score: {similarity_score:.2f}")
                if similarity_score <= 0.30:
                    alert()
            k += 1  # Move to the next entry
        else:
            print(f"No data for Entry {k}. Retrying...")
            time.sleep(2)
    except Exception as e:
        print(f"Error: {e}. Retrying...")
        time.sleep(5)

# @title
import firebase_admin
from firebase_admin import credentials, db
!pip install twilio
from twilio.rest import Client


# Find your Account SID and Auth Token at twilio.com/console
# and set the environment variables. See http://twil.io/secure

def alert():
    account_sid ="ACd0820c8fb546c38be1760536009548cc"
    auth_token ="a07946d79b75d7a24937ba7ffcf5f083"
    client = Client(account_sid, auth_token)

    call = client.calls.create(
                            twiml='<Response><Say>You are recieving this call because there has been a suspicious entry at the door please be alerted</Say></Response>',
                            to='+918247341184',
                            from_='+15856693126'
                        )
# Firebase credentials directly in the code (not recommended for production)
firebase_credentials = {
  "type": "service_account",
  "project_id": "adpsr-75e1f",
  "private_key_id": "4090e7b1b73e8f141c8df9fde567201ef7205121",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC2cSpvHTPAytJi\nvKDu/xVCe6X1zlx3+mGhdUfENctd+4Q/u7PyE1K4F+epk2mFpMeIPAmk7zQg+ebz\nwUrr1hxL0O8CMLbXtJWL5uRinTcjoo5wwAnDxENvEoSQrekI4x5WMThVugTgyPN6\nKnxXb6f/IK9QM9X/NOP5ocunl5kyRhHN3Vm/HQofgWbjhnIkGWmy/b4Fr4bdTdUk\nhYcpbKcspv19mDmBuJiQs/unxSlb9DQSZ5to74rEH0YGWVufOZQFwfVvEb8gpmr3\nLqZo62s3iNdXfouM5rVUlNI/tFowZwwOsiG0x+3Mat+MpEF2oKUWCG86KS54tyOP\nWTOxvUJBAgMBAAECggEAGfJJNyk/iX0u45TxDFxhwSVFqooxM2z8ApLj5H9ED3cs\nTUYcJuLhokXgEAljefq/19u2AWt1jfUMiAEm7xhxyMSLoVOdRVss44swUugKBfrh\n6B4fpWRdtMe867iYCkgGsfppCSQd+nwJyIePTH4YNdwHos/kcNmsTH3asViJlJEN\nnsqRstqdt7Pj2JJkS4VXIPU0liUIeWLuhrF6YB9FqWvszBAeDt3ts2Q3xtrzo69g\n78nTkzpYepAJ64SF572HmcI320N6R+odkYhJMuhhjZ7HprOoXyEv2BlPCfqR5nDv\nUyAI9UhLEiPCrK55MioNMCBOUKArcDNMk0NgBSSAAwKBgQDz1ciVAPCi3ab5W5KB\nsfIer0aIKWKLpimOg4Uv2VxUdnbah7ZhWkVWYPsJ1wmWbiT4Izv0SKlmkIcoO9x8\nzVL4otVoSC/CYBv8Ba6QTwzvtAhetDDseXan8P3HJEHeQLj8WZluMdSAGbHh2QUb\n93ny3rwFU57F+SK/m/b5yGU0hwKBgQC/i0ghf7FPnRtweJQ1f6nID4DW7WGpAseb\nW+/mjATLDNQFroNl5QJwTq3igDj8QjMHmzZh1zq8uYF/kdADW02OIEElAAI7SD20\n5WRFM1QDEuF2DntrY98LY844L3CQlzOfc2oi+ZW3pzD/HiVSqUqcyZIVan1HDET6\nSTelRuTM9wKBgQCL4Ow8blmdVMJg8iNNu6NF7w7rNbKOojfcxZ42IN9SpNLx8kCy\nAHMeZmwc7PtXDMCwiKXwMW7co7SlZBHMlo0ujVsXg7HCNBhZr3jA2Fh3ejQDACPA\nxL1JAnrTLv2KXl7AhTX7fSKGijb9dN31eTbAGP6Ln7jJoW5JtVMtX8SPKQKBgQCI\npPM7Op4ifqDRlqOcmstjNnQiX8xYxuvhEDBPlzngJPGob/u7GCmqNubje7erdgpz\nda3RFLsJYYlZmYr8qgjkyGvQ2nW9Fuc2gqMKnvhjDPgcwW4YiXHX7UZzXJx/+e3Q\n5YQlGUpObw6MIVRc6PqaaU42yvY+VilrKApzdOTKtwKBgQDtOoFM4v8x+7CRb2dC\nRkL80lZDlWRnQJhFXbz2d7Gdpfnhg0S5L3E+3HPZ+L0RVSRSPcgDkcYQE/hy1Wpa\nxE5wsp3SRGWjJS8g+Cry8OepoAIYmdELNKTRyD9wqZjMK/wnSmsyIOqKtsFgdy4v\n1EU7MtRiOIbUc2hF6S80y4bMFA==\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-7fyvc@adpsr-75e1f.iam.gserviceaccount.com",
  "client_id": "107099221824990410869",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-7fyvc%40adpsr-75e1f.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}


# Initialize Firebase Admin SDK if not already initialized
if not firebase_admin._apps:
    cred = credentials.Certificate(firebase_credentials)
    firebase_admin.initialize_app(cred, {
        'databaseURL': 'https://adpsr-75e1f-default-rtdb.firebaseio.com/'
    })

# Function to fetch data from Firebase Realtime Database
def fetch_data_from_firebase(path):
    ref = db.reference(path)  # Specify the database path
    data = ref.get()
    return data

# Comparison function to calculate similarity
def compare(value):
    expected_password = "6754"
    count = 0
    # Convert strings to lists for modification
    expected_password_list = list(expected_password)
    value_list = list(value)
    for i in range(0,len(expected_password),1):
        for j in range(0,len(value),1):
          if value_list[j] == expected_password_list[i]:
              count += 1
              # Modify the lists instead of the original strings
              expected_password_list[i]='&'
              value_list[j]='.'
    return (count / len(value))

# Fetch specific data
status_data = fetch_data_from_firebase('Entries/Entry5/typed')

print("Status Data:")
for key, value in status_data.items():
    # if key == "typedpassword":
        print(f"  Key: {key}, Value: {value}")
        similarity_score = compare(value)
        print(f"Similarity Score: {similarity_score:.2f}")
        if(similarity_score <= 0.30):
          alert();
          break;

# @title
import firebase_admin
from firebase_admin import credentials, db
#!pip install twilio
from twilio.rest import Client


# Find your Account SID and Auth Token at twilio.com/console
# and set the environment variables. See http://twil.io/secure

def alert():
    account_sid ="ACd0820c8fb546c38be1760536009548cc"
    auth_token ="a07946d79b75d7a24937ba7ffcf5f083"
    client = Client(account_sid, auth_token)

    call = client.calls.create(
                            twiml='<Response><Say>You are recieving this call because there has been a suspicious entry at the door please be alerted</Say></Response>',
                            to='+918247341184',
                            from_='+15856693126'
                        )
# Firebase credentials directly in the code (not recommended for production)
firebase_credentials = {
    "type": "service_account",
    "project_id": "adpsr-75e1f",
    "private_key_id": "4090e7b1b73e8f141c8df9fde567201ef7205121",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADAN...",
    "client_email": "firebase-adminsdk-7fyvc@adpsr-75e1f.iam.gserviceaccount.com",
    "client_id": "107099221824990410869",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-7fyvc%40adpsr-75e1f.iam.gserviceaccount.com",
    "universe_domain": "googleapis.com"
}

# Initialize Firebase Admin SDK if not already initialized
if not firebase_admin._apps:
    cred = credentials.Certificate(firebase_credentials)
    firebase_admin.initialize_app(cred, {
        'databaseURL': 'https://adpsr-75e1f-default-rtdb.firebaseio.com/'
    })

# Function to fetch data from Firebase Realtime Database
def fetch_data_from_firebase(path):
    ref = db.reference(path)  # Specify the database path
    data = ref.get()
    return data

# Comparison function to calculate similarity
def compare(value):
    expected_password = "1243"
    count = 0
    # Convert strings to lists for modification
    expected_password_list = list(expected_password)
    value_list = list(value)
    for i in range(0,len(expected_password),1):
        for j in range(0,len(value),1):
          if value_list[j] == expected_password_list[i]:
              count += 1
              # Modify the lists instead of the original strings
              expected_password_list[i]='&'
              value_list[j]='.'
    if(len(value)==0):
       return 0
    return (count / len(value))

# Fetch specific data
k=0
while(True):
   status= fetch_data_from_firebase('Entries/Entry'+str(k)+'/typed')
   k=k+1
   print(k)
   if status is not None:
      print("nn")
      status_data=status
      break

   else:
      print("do")



print("Status Data:")
if status_data is not None:
  for key, value in status_data.items():
      # if key == "typedpassword":
          print(f"  Key: {key}, Value: {value}")
          similarity_score = compare(value)
          print(f"Similarity Score: {similarity_score:.2f}")
          if(similarity_score <= 0.30):
            alert()

# @title

# Comparison function to calculate similarity
def compare(value):
    expected_password = "hielo"
    count = 0
    for i in range(0,len(expected_password),1):
        for j in range(0,len(value),1):
          if value[j] == expected_password[i]:
              count += 1
              #expected_password[i]='&'
    return (count / len(value))*100
input_password ="hiels"
similarity_score = compare(input_password)
print(f"Similarity Score: {similarity_score:.2f}")